name: IllegalFucker
version: '${project.version}'
main: me.sevj6.illegalfucker.IllegalFucker
authors: [ SevJ6 ]
description: A base plugin with gradle as the build system
load: POSTWORLD
depend:
  - PaperAPIExtentions